### ISSUE TITLE
Corrupted repository?

### ISSUE THREAD

**Issue by jurra** [goscommons/Grapples#21] opened 2018-05-13 07:14 UTC
I had a problem when pulling this repository in my pc when updating with the last version of the repository:
Does anyone has same problem when pulling?
![image](https://user-images.githubusercontent.com/18581201/39964853-d4860978-568d-11e8-8c6a-8e92e77f22de.png)

**Comment by polemidis** [comment] 2018-05-16 16:25
I think we should close this also. It was not a bug but the relocation of the files in the branch, without getting up to date with the master which had some names changed, and our ignorance on how to resolve this

**Comment by jurra** [comment] 2018-05-16 17:08
are you still having this error?
I am still having it

**Comment by polemidis** [comment] 2018-05-17 02:36
I dont.

**Closed** 2018-05-17 05:42 UTC
Labels: bug
